[env:esp32-c6]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    lvgl/lvgl@^9.1.0
    lovyan03/LovyanGFX@^1.1.12

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_USE_LOG=0