[env:esp32-c6-devkitc-1]
platform="https://github.com"
platform_packages=framework-arduinoespressif32@https://github.com
board=esp32-c6-devkitc-1
framework=arduino
monitor_speed=115200

lib_deps=
    bodmer/TFT_eSPI@^2.5.43

build_flags=
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=172
    -DTFT_HEIGHT=320
    -DTFT_RGB_ORDER=TFT_BGR
    -DTFT_BL=22
    -DTFT_MOSI=6
    -DTFT_SCLK=7
    -DTFT_CS=14
    -DTFT_DC=15
    -DTFT_RST=21
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DSPI_FREQUENCY=40000000